BlogApp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.core.urlresolvers import reverse
from django.views.generic.edit import CreateView
from django.views.generic.base import RedirectView

from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import UserCreationForm

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='login')),
    url(r'^accounts/register/', CreateView.as_view(
        template_name='register.html',
        form_class=UserCreationForm,
        success_url= '/blog/'
    ), name='register'),
	url(r'^accounts/login/', auth_views.login, {
        'template_name' : 'login.html'
    }, name='login'),
	url(r'^accounts/logout/', auth_views.logout_then_login, name='logout'),
	url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^admin/', include(admin.site.urls)),
]

blog/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^$', login_required(views.IndexView.as_view()), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', login_required(views.PostView.as_view()), name='post'),
    url(r'^new/$', views.addPost, name='addPost'),
    url(r'^(?P<post_id>[0-9]+)/modify/$', views.modifyPost, name='modifyPost'),
    url(r'^(?P<post_id>[0-9]+)/delete/$', views.deletePost, name='deletePost'),
    url(r'^(?P<post_id>[0-9]+)/comments/$', views.addComment, name='postComment'),
    url(r'^comments/(?P<comment_id>[0-9]+)/reply/$', views.addComment, name='replyToComment'),
    url(r'^comments/(?P<comment_id>[0-9]+)/modify/$', views.modifyComment, name='modifyComment'),
    url(r'^comments/(?P<comment_id>[0-9]+)/delete/$', views.deleteComment, name='deleteComment'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
	author = models.ForeignKey(User)
	title = models.CharField(max_length=100)
	body = models.TextField()
	pub_date = models.DateTimeField('date published', auto_now_add=True)
	modified_date = models.DateTimeField('date modified', auto_now=True)

	def __unicode__(self):
		return self.title

class Comment(models.Model):
	author = models.ForeignKey(User)
	body = models.TextField()
	pub_date = models.DateTimeField('date published', auto_now_add=True)
	modified_date = models.DateTimeField('date modified', auto_now=True)

	def __unicode__(self):
		return ' '.join(self.body.split()[:4]) + '...'

class PostComment(models.Model):
	post = models.ForeignKey(Post)
	comment = models.ForeignKey(Comment)
	pub_date = models.DateTimeField('date posted', auto_now_add=True)


class Reply(models.Model):
	reply = models.ForeignKey(Comment, related_name='parent_comments')
	comment = models.ForeignKey(Comment, related_name= 'replies')
	pub_date = models.DateTimeField('date posted', auto_now_add=True)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.core.urlresolvers import reverse
from django.http import Http404

from django.contrib.auth.decorators import login_required

from .models import Post, Comment, PostComment, Reply

class IndexView(generic.ListView):
	template_name = 'blog/index.html'
	context_object_name = 'latest_blog_posts'

	def get_queryset(self):
		return Post.objects.order_by('-pub_date')

class PostView(generic.DetailView):
	model = Post
	template_name = 'blog/post.html'

@login_required
def addPost(request):
	print(request.user);
	if(request.method == 'GET'):
		# render form
		return render(request, 'blog/new_post.html')
	elif(request.method == 'POST'):
		# save new post
		Post.objects.create(author=request.user, title=request.POST['title'], body=request.POST['body'])
		return redirect(reverse('blog:index'))
	else:
		raise Http404()

@login_required
def modifyPost(request, post_id):
	post = get_object_or_404(Post, pk=post_id)
	checkAuthor(request, post)
	if(request.method == 'GET'):
		# render form
		return render(request, 'blog/new_post.html', {
			'post' : post,
		})
	elif(request.method == 'POST'):
		# update post
		post.body = request.POST['body']
		post.save()
		return redirect(reverse('blog:post', args=(post_id,)))
	else:
		raise Http404()

@login_required
def deletePost(request, post_id):
	post = get_object_or_404(Post, pk=post_id)
	checkAuthor(request, post)
	post.delete()
	return redirect(reverse('blog:index'))

@login_required
def addComment(request, post_id=None, comment_id=None):
	next = getNextURL(request)
	if(request.method != 'POST'):
		raise Http404();
	new_comment = Comment.objects.create(author=request.user, body=request.POST['body'])
	if(post_id):
		# add comment to post
		post = get_object_or_404(Post, pk=post_id)
		PostComment.objects.create(post=post, comment=new_comment)
	elif(comment_id):
		# add reply to comment
		comment = get_object_or_404(Comment, pk=comment_id)
		Reply.objects.create(comment=comment, reply=new_comment)
	return redirect(next)

@login_required
def modifyComment(request, comment_id):
	next = getNextURL(request)
	comment = get_object_or_404(Comment, pk=comment_id)
	checkAuthor(request, comment)
	comment.body = request.POST['body']
	comment.save()
	return redirect(next)

@login_required
def deleteComment(request, comment_id):
	next = getNextURL(request)
	comment = get_object_or_404(Comment, pk=comment_id)
	checkAuthor(request, comment)
	comment.delete()
	return redirect(next)

def checkAuthor(request, obj):
	''' Checks if the given post/comment was authored by the logged in user '''
	if(request.user.id != obj.author.id):
		raise Http404('You are not authorized to perform this action')

def getNextURL(request):
	''' Gets the url specified by 'next' GET parameter; uses default otherwise '''
	try:
		next = request.GET['next']
	except KeyError:
		return reverse('blog:index')
	return next;

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Simple Blog{% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/semantic.min.css' %}">
	<script type="text/javascript" src="{% static 'blog/js/jquery.js' %}"></script>
	{% block morestaticfiles %}{% endblock %}
</head>
<body>
<div class="ui grid">
	<div class="three wide column">
		{% include 'blog/sidebar.html' %}
	</div>
	<div id="main-content" class="nine wide column">
	{% block content %}
	{% endblock %}
	</div>
</div>
</body>
</html>

blog/templates/blog/comments/add_comment_form.html
<h2>Add Comment</h2>
<form action="{% url 'blog:postComment' post.id %}?next={% url 'blog:post' post.id %}" method="POST">
	{% csrf_token %}
	<div class="ui form">
		<div class="field">
			<textarea name="body"></textarea>
		</div>
		<div class="field">
			<input class="ui button" type="submit" value="Post Comment">
		</div>
	</div>
</form>

blog/templates/blog/comments/edit_form.html
<form class="editForm" action="{% url 'blog:modifyComment' comment.id %}?next={% url 'blog:post' post.id %}" method="POST">
	{% csrf_token %}
	<div class="ui form">
		<div class="field">
			<textarea name="body">{{ comment.body }}</textarea>
		</div>
		<div class="field">
			<input class="ui button" type="submit" value="Edit">
		</div>
	</div>
</form>

blog/templates/blog/comments/index.html
<h2>Comments</h2>
<ul>
{% for comment in post.postcomment_set.all %}
	<li>
		{% include 'blog/comments/show_comment.html' with comment=comment.comment %}
	</li>
{% empty %}
	<li>No Commments</li>
{% endfor %}
</ul>

{% include 'blog/comments/add_comment_form.html' %}

blog/templates/blog/comments/reply_form.html
<form class="replyForm" action="{% url 'blog:replyToComment' comment.id %}?next={% url 'blog:post' post.id %}" method="POST">
	{% csrf_token %}
	<div class="ui form">
		<div class="field">
			<label>Reply</label>
			<textarea name="body"></textarea>
		</div>
		<div class="field">
			<input class="ui button" type="submit" value="Post Reply">
		</div>
	</div>
</form>

blog/templates/blog/comments/show_comment.html
{{ comment.body }} - {{ comment.author.username }}
<a href="" class="replyToggle">Reply</a>
{% if user.id == comment.author.id %}
{% include 'blog/comments/edit_form.html' %}
<a href="" class="editToggle">Edit</a>
<a href="{% url 'blog:deleteComment' comment.id %}?next={% url 'blog:post' post.id %}">Delete</a>
{% endif %}
{% include 'blog/comments/reply_form.html' %}
<ul>
{% for reply in comment.replies.all %}
	<li>
		{% include 'blog/comments/show_comment.html' with comment=reply.reply %}
	</li>
{% endfor %}
</ul>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}

<h1>Recent Posts</h1>
{% if latest_blog_posts %}
	<ul>
	{% for post in latest_blog_posts %}
		<li><a href="{% url 'blog:post' post.id%}">{{ post.title }}</a></li>
		<span>By {{ post.author.username }} on {{ post.pub_date }}</span>
	{% endfor %}
	</ul>
{% else %}
<p>No posts yet</p>
{% endif %}

{% endblock %}

blog/templates/blog/new_post.html
{% extends 'blog/base.html' %}

{% load staticfiles %}

{% block morestaticfiles %}
<script type="text/javascript" src="{% static 'blog/js/lorem.js' %}"></script>
<script type="text/javascript" src="{% static 'blog/js/index.js' %}"></script>
{% endblock %}

{% block content %}

<form action="{{ action }}" method="POST">
	<fieldset>
		{% csrf_token %}
		<div class="ui form">
			<div class="field">
				<label for="title">Title</label>
				<input id="title" type="text" name="title" value="{{ post.title }}" required>
			</div>
			<div class="field">
				<label for="post-body">Content</label>
				<textarea id="post-body" name="body" required>{{ post.body }}</textarea>
			</div>
			<div class="field">
				<button class="ui button addLorem">Lorem Ipsum</button>
				<input class="ui button" type="submit">
			</div>
		</div>
	</fieldset>
</form>
{% endblock %}

blog/templates/blog/post.html
{% extends 'blog/base.html' %}

{% load staticfiles %}

{% block morestaticfiles %}
<script type="text/javascript" src="{% static 'blog/js/index.js' %}"></script>
{% endblock %}

{% block content %}

<h1>{{ post.title }}</h1>
{% if user.id == post.author.id %}
<a href="{% url 'blog:modifyPost' post.id %}">Edit</a>
<a href="{% url 'blog:deletePost' post.id %}">Delete</a>
{% endif %}
<p>Posted By {{ post.author.username }}</p>
<p>{{ post.body }}</p>

{% include 'blog/comments/index.html' %}

{% endblock %}

blog/templates/blog/sidebar.html
<div class="ui fixed vertical menu">
	<a class="item" href="{% url 'blog:addPost' %}">Write New Post</a>
	<a class="item" href="{% url 'blog:index' %}">Blog</a>
	<a class="item" href="{% url 'logout' %}">Logout</a>
</div>

templates/base_accounts.html
{% extends 'base_site.html' %}

{% block title %}
Login
{% endblock %}

{% block head %}
<style type="text/css">
  body {
    background-color: #DADADA;
  }
  body > .grid {
    height: 100%;
  }
  .column {
    max-width: 450px;
  }
</style>
{%  endblock %}

{% block content %}
<div class="ui middle aligned center aligned grid">
  <div class="column">
    <h2 class="ui teal image header">
      <div class="content">
        {% block header %}{% endblock %}
      </div>
    </h2>
    <form class="ui large form error" action="{{ actionUrl }}" method="POST">
      {% csrf_token %}
      <div class="ui stacked segment">
        {% block form_content %}{% endblock %}
      </div>

      {% block form_errors %}{% endblock %}

    </form>

    {% block messages %}{% endblock %}

  </div>
</div>
{% endblock %}

templates/base_site.html
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properities -->
  <title>SimpleBlogger | {% block title %}Blog{% endblock %}</title>

  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'blog/css/semantic.min.css' %}">
  
  {% block head %}  {% endblock %}

</head>
<body>

{% block content %}{% endblock %}

{% include 'googleanalytics.html' %}

</body>
</html>

templates/googleanalytics.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67522730-1', 'auto');
  ga('send', 'pageview');

</script>

templates/login.html
{% extends 'base_accounts.html' %}

{% block title %}Login{% endblock %}

{% block header %}Login to your account{% endblock %}

{% block form_content %}
  <div class="field">
    <div class="ui input">
      <input type="text" name="username" placeholder="Username" required>
    </div>
  </div>
  <div class="field">
    <div class="ui input">
      <input type="password" name="password" placeholder="Password" required>
      <input type="hidden" name="next" value="{{ next }}" />
    </div>
  </div>
  <input type="submit" value="Login" class="ui fluid large teal submit button">
{% endblock %}

{% block form_errors %}
  {% if form.non_field_errors %}
  <div class="ui error message">
    <ul class="list">
    {% for error in form.non_field_errors %}
    <li>
        {{ error }}
    </li>
    {% endfor %}
    </ul>
  </div>
  {% endif %}
{% endblock %}

{% block messages %}
  <div class="ui message">
    New to us? <a href="{% url 'register' %}">Sign Up</a>
  </div>
{% endblock %}

templates/register.html
{% extends 'base_accounts.html' %}

{% block title %}Sign Up{% endblock %}

{% block header %}Create New Account{% endblock %}

{% block form_content %}
  <div class="field">
    <div class="ui input">
      <input type="text" name="username" placeholder="Username" required>
    </div>
  </div>
  <div class="field">
    <div class="ui input">
      <input type="password" name="password1" placeholder="Password" required>
      <input type="hidden" name="next" value="{{ next }}" />
    </div>
  </div>
  <div class="field">
    <div class="ui input">
      <input type="password" name="password2" placeholder="Password Confirmation" required>
      <input type="hidden" name="next" value="{{ next }}" />
    </div>
  </div>
  <input type="submit" value="Sign Up" class="ui fluid large teal submit button">
{% endblock %}

{% block form_errors %}
  {% if form.errors %}
  <div class="ui error message">
    {% for key,error in form.errors.iteritems %}
      {{ error }}
    {% endfor %}
  </div>
  {% endif %}
{% endblock %}